index.js, package-lock.json, package.json
For my use case I needed the output to pipe directly to the processes output instead of waiting for the command to finish. I also ran into a maxBuffer issue due to the use of `exec` so I switched it to spawn.
This should help with #15 and #14
=> spawn instead of exec and piping child process output

index.js, test/build-test.Dockerfile, test/docker-compose-build.yml, test/index.js
I used argument name `service` because of issue #9. I can change it to container to match the other methods if you would like.
If TypeScript was used (#10) the signature for the build function could be specified like so:
```TypeScript
build(service: string, options: IBuildOptions): Promise<string>
build(services: string[], options: IBuildOptions): Promise<string>
build(options: IBuildOptions): Promise<string>
build(arg0: string|string[]|IBuildOptions, arg1?: options: IBuildOptions) {
// ...
}
```
I can understand not wanting to use the same name for each of the above signatures. I can rename them to `buildOne()`, `buildMany()`, `buildAll()` if you'd like.
=> docker-compose build support

readme.md
I'm assuming this was an old API that was changed? In any case, this is more copy-pastable :)
=> docs(readme): fix example

index.d.ts, index.js
- Added the `push` command to allow to push docker-compose to local or remote registries
- Added `options.parallel` as an optional option for buildAll and buildMany to parallel-ize building multiple images.
- Update index.d.ts
I wasn't sure if/how to add tests for push without either having (1) a remote registry available to push to or (2) spinning up a local registry somehow but for now there's no changes to the tests.
=> Added push command, updated build to allow parallel builds

index.d.ts, index.js, test/docker-compose-2.yml, test/index.js
Adds the port command, closes #51
=> Add port command

index.js
=> Fix trailing commas causing syntax error on NodeJS 6.x

index.d.ts
Realized that declaration files for `logs` function requires 3 arguments instead of correct 2 when checking tests
=> Fix declaration for `logs` function

index.d.ts, index.js, readme.md
Expands on #38 to add logging for multiple services simultaneously. One nice feature about `docker-compose` logs is that when launched simultaneously for multiple services, they are automatically color-coded. This feature is lost in the initial implementation found in #38 where one can only log one service at a time. This PR keeps the same interface but accounts for the fact that one can pass a single service or an array of services as a parameter, and the code will handle both cases providing the added benefit of automatic color-coding when passing an array of services.
Tested and working as expected.
Also corrected two minor typos from the previous PR referred above.
=> BLD: add support for logging for multiple services

index.d.ts
`fieldName: ?number` is not a valid type expression. I assume this was a mistake, but in any case it will fail in TypeScript projects with the error `JSDoc types can only be used inside documentation comments.`.
=> Fix TypeScript typings for DockerComposeResult

package.json, tsconfig.json
two minor changes to make the build more resilient:
* fix linting after build was called
* use proper es2015 library (for Promises, etc.) in tsconfig
=> Fix linting issues after build, import proper es2015 lib

src/index.ts, test/index.test.ts
I'm working on some user-facing software that I want to be able to do a quick smoke test and make sure they're running Docker as a part of the app startup. I figured running version was the safest check, but was surprised to see there wasn't a way to do that yet with this library, so this is just a little add.
I figure it may also come in handy in the future if we require a certain version for a specific docker-compose feature, and need to ask the user to upgrade.
=> Add a 'version' function

package.json
**composefile** isn't needed for this package to work.
=> chore(deps): remove useless dependency

src/index.ts
The flag `--no-start` in the up command is also incompatible with `-d`
```bash
$ docker-compose up --no-start -d
ERROR: --no-start and --detach cannot be combined.
```
=> Update flags incompatible with detached mode

package.json, readme.md, src/index.ts, test/index.test.ts
Addresses this issue: https://github.com/PDMLab/docker-compose/issues/109
Probably not properly linted because of https://github.com/PDMLab/docker-compose/issues/123
=> feat: allow to pass docker compose configuration as string

readme.md
Adds the `port` command to the list of supported commands. We didn't realize this existed, so had used `docker-compose port ...` directly.
=> Add port to supported commands

.github/workflows/ci.yml, yarn.lock
```
❯ yarn build
yarn run v1.22.5
$ tsc
node_modules/@types/fs-extra/index.d.ts:243:49 - error TS2694: Namespace '"fs"' has no exported member 'RmOptions'.
243 export function rm(path: PathLike, options?: fs.RmOptions): Promise<void>;
~~~~~~~~~
Found 1 error.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
=> Fix broken build

src/index.ts, test/index.test.ts
closes #174
This PR adds functionality to pause (`.pauseOne`) and un-pause (`.unpauseOne`) a single container.  The method used is very similar to the existing `.stopOne` function. 
A new test has been incorporated which stops the proxy container and then attempts a `cat /etc/os-release` command.  This should fail because the container is paused, with an error that state the container is paused.  The test then un-pauses the container and checks that the same command now succeeds.
The ability to (un)pause a container is useful for testing whether an application can re-synchronise after missing some incoming data.
=> feat: single container pause and unpause added

docs/README.md
This PR mainly:
* fix the `port` command options
* order the command list alphabetically
I also wanted to update the `rm` command doc, but I was not sure how to document it...
=> Update commands documentation

docs/README.md, src/index.ts, test/index.test.ts
* add stopMany command
* update documentation to include stopMany
* add stopMany test
=> feat: stop many

src/index.ts, test/index.test.ts
* fix error `trim on undefined` when ps is used with options `--services`
* added tests for `ps --services` output
=> fix: ps --services trim on undefined

.github/workflows/ci.yml
this will also upgrade `docker-compose` v1 to `1.29.2`
=> ci: use github runner on ubuntu 22.04

src/v2.ts
In the v2 api there is a `console.log` making it hard to integrate in own applications.
=> Remove unnecessary console.log in v2 api

docs/api.md, readme.md, src/v2.ts, test/v2/compose.test.ts
This pull requests adds support for `--format json` so that the output can be more consistent concerning the state.
In addition it exports the single `DockerComposePsResultService` as type 
Notes:
- local tests do not work for me (neither before nor after I started the modifications)
- the `state` from the plain text ps output is probably not correct: a typical output is `Up 3 hours` but should be `running`. I did not try to correct this.
=> feat: ps supports json format

src/index.ts, src/v2.ts
My project needs the flexebility to run docker inside of wsl for that i run docker as `wsl docker compose ...`
Now this is possible by running for example:
```javascript
compose.upAll({
executable: {
executablePath: "wsl",
options: ["docker"]
}
})
```
=> More flexibility in process creation

CHANGELOG.md, src/v2.ts
The removal of the down() method broke the @wordpress/env package. Surely more packages got broken by that. This PR will add the down() method as alias of the downAll method.
=> add method alias down for downAll

docs/api.md, src/v2.ts, test/v1/index.test.ts, test/v2/compose.test.ts
implements #267 
- adds `compose images` support
- adds `compose create` support
Logic and tests are implemented based on the `ps` command
=> images & create* commands

src/index.ts, src/v2.ts, test/v2/compose.test.ts, test/v2/docker-compose-echo.yml
I've tried to also create a suit of tests, but they are a bit wacky (btw, the original tests didn't run fully ok for me - didn't investigate why)
=> not starting with -d when incompatible flags are set

docs/api.md, src/index.ts
=> Add service `stats` support

readme.md, src/index.ts
=> feat: using standalone binary

src/index.ts, test/compose.test.ts
closes #301 
Please note: tests are failing for me locally on `master`, but I did run the logs tests with `describe.only` and they pass. So failures seem to be unrelated to my changes...
My env is ubuntu 24.04 and:
```
Docker version 28.3.3, build 980b856
Docker Compose version v2.39.1
node --version -> v22.17.1
```
=> feat: add --timestamps to log option
