index.js
package-lock.json
package.json
readme.md
test/docker-compose-2.yml
test/index.js

```javascript
// for every compose command
command.up({
cwd: '.',
config: 'docker-compose.2.yml',
// or
config: ['docker-compose.main.yml', 'docker-compose.db.yml']
})
```
https://github.com/PDMLab/docker-compose/issues/1

Custom and multiple YML files support

---

index.js
package-lock.json
package.json
readme.md
test/docker-compose-2.yml
test/docker-compose.yml
test/index.js

Support for basic `docker-compose run` and `docker-compose exec`
readme.md updated with details
Should be merged after https://github.com/PDMLab/docker-compose/pull/2

run and exec support

---

index.js

Exposed the 'env' option on child_process.exec

---

package-lock.json
package.json

fix deps with CVEs (lodash/debug)

---

index.d.ts
package.json

TypeScript type declarations for the library. Ref #10

typescript declarations

---

index.d.ts

update Typescript typings

---

index.d.ts
index.js
test/index.js

implement restart command

---

index.d.ts
index.js
readme.md
test/index.js

add support to pass docker-compose command options

---

test/docker-compose.yml

fix broken "ensure run and exec are working" test

---

.npmignore

exclude IDE and CI settings from npm publish

---

index.d.ts

make typings work in local tests

---

index.d.ts
index.js
readme.md
test/docker-compose-42.yml
test/index.js

Add config command & related

---

test/build-test.Dockerfile
test/docker-compose-2.yml
test/docker-compose-42.yml
test/docker-compose.yml
test/index.js

Use same docker image versions for tests

---

CHANGELOG.md
index.d.ts
index.js
readme.md
test/index.js

Resolves #58. It's a pretty straight-forward addition.
I'll try to add a test for returning different exit codes.

Expose docker-compose exit code in results

---

index.d.ts
index.js
test/index.js

This is the same as #73, with all requested changes implemented.

Allow passing an array as command to run and exec

---

src/index.ts

Fix interfaces not being exposed in typings file

---

readme.md
src/index.ts
test/index.test.ts

Add stopOne() command

---

package-lock.json

https://npmjs.com/advisories/1118

fix eslint-utils security issue

---

readme.md

add pull command methods to readme

---

readme.md

Fix a copy-paste typo for pull commands

---

package-lock.json
package.json
readme.md

enforce conventional commit messages

---

src/index.ts
test/index.test.ts

feat: add ability to pass --abort-on-container-exit flag to up methods

---

package-lock.json
package.json
src/index.ts
test/index.test.ts

feat: allow passing service names to `rm` function

---

package.json
src/index.ts
test/docker-compose-2.yml
test/docker-compose-42.yml
test/docker-compose.yml
test/index.test.ts
yarn.lock

Make results type safe

---

docs/README.md
src/index.ts

Add config option to set exec path of docker-compose exec

Add Exec path option

---

src/index.ts

Expose execCompose function

---

src/index.ts

Avoids issues like https://github.com/PDMLab/docker-compose/issues/161
Also closes #161

feat(dx): add default export

---

docs/README.md
src/index.ts
test/index.test.ts

feat: passing callback to report progress

---

readme.md

https://github.com/badges/shields/issues/8671

chore: update build badge due to breaking change

---

readme.md

gitter.im will no longer be monitored

docs: add discord server link

---

docs/api.md

Sorry, completely forgot to fix the typo in #245

Fix typo in docs

---

src/v2.ts
test/v2/compose.test.ts

I think i did this all correctly, though not fully sure
https://github.com/PDMLab/docker-compose/issues/259
I also updated down to downAll, that would be breaking so not sure how that should be handled

Adding downOne and downMany, renamed down to downAll
